apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagenet-inference
  labels:
    app: imagenet-inference
spec:
  replicas: 2   
  selector:
    matchLabels:
      app: imagenet
  template:
    metadata:
      labels:
        app: imagenet
    spec:
      containers:
      - name: imagenet-inference
        image: avantikaaxx/imagenet_a
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/var/sharedlib"
          name: "sharedspace"
      volumes: 
      - name: sharedspace